dataset: meta-mini-imagenet
test:
  split: meta-test
  image_size: 84
  normalization: False
  transform: null
  n_batch: 600 # original value 150
  n_episode: 1 # original value 4
  n_way: 5
  n_shot: 5
  n_query: 5

load: ./save/convnet4_mini-imagenet_5_way_5_shot/max-va.pth

inner_args:
  n_step: 10
  encoder_lr: 0.01
  classifier_lr: 0.01
  first_order: False
  frozen:
    - bn # default 
    # - conv1
    # - conv2
    # - conv3
    # - conv4

epoch: 1